name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install musl
        run: sudo apt update -y && sudo apt install -y musl-tools
      - name: install rust-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Cache Vendor
        uses: actions/cache@v4.0.2
        id: cache-vendor
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            .cargo
            vendor
          # An explicit key for restoring and saving the cache
          key: vendorcache-${{ hashFiles('Cargo.*') }}
          # Run the post step to save the cache even if another step before fails
          save-always: true
      - name: vendor
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: (mkdir .cargo || true) && cargo vendor --locked > .cargo/config
      - name: Cache Target
        uses: actions/cache@v4.0.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: target
          # An explicit key for restoring and saving the cache
          key: targetcache
          # Run the post step to save the cache even if another step before fails
          save-always: true
      - name: Build
        run: cargo build --target x86_64-unknown-linux-musl --release
      - name: Build Client
        run: cargo build --target x86_64-unknown-linux-musl --release --package in-mem-client
      - uses: actions/upload-artifact@v4
        with:
          name: in-mem
          path: target/x86_64-unknown-linux-musl/release/in-mem
      - uses: actions/upload-artifact@v4
        with:
          name: in-mem-client
          path: target/x86_64-unknown-linux-musl/release/in-mem-client
